rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /data/local_disk
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
live_rooms:
- url: https://www.douyu.com/topic/hysjc?rid=3652542
  is_listening: true
out_put_tmpl: tmp/{{ .Live.GetPlatformCNName }}/{{ .HostName | filenameFilter }}/{{ now | date "20060102-150405"}}-{{ .RoomName | filenameFilter }}.flv
video_split_strategies:
  on_room_name_changed: false
  max_duration: 1h30m0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000
